export const foodCategories = [
    "North Indian",
    "South Indian",
    "Chinese",
    "Italian",
    "Mexican",
    "Thai",
    "Continental/European",
    "Middle Eastern",
    "Breakfast",
    "Lunch",
    "Dinner",
    "Snacks",
    "Desserts/Sweets",
    "Brunch/All-Day Breakfast",
    "Biryani/Rice Bowls",
    "Fast Food",
    "Healthy/Diet Options",
    "Vegan",
    "Fusion/Contemporary",
    "Local Favorites",
    "Trending/Popular"
  ];